### ISSUE TITLE
Building a production bundle in the graphql-server example fails.

### ISSUE THREAD

**Issue by birdiesanders** [reactql/examples#2]
First off, this is the best boilerplate I've come across, keep up the hard work! 

I have a clone of the project, and while dev works perfectly, building a static bundle or running in production both fail with the same error. 

```
birdie@nanday:~/soapql/graphql-server> npm run build-run

graphql-server@0.1.0 build-run /home/birdie/soapql/graphql-server
cross-env NODE_ENV=production WEBPACK_CONFIG=browser_prod,server_prod webpack --colors && npm run server

Error: browser_prod.js not found or has errors:
{ Error: Cannot find module 'kit/lib/env'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/birdie/soapql/graphql-server/config/project.js:7:1)
    at Module._compile (module.js:569:30)
    at loader (/home/birdie/soapql/graphql-server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/birdie/soapql/graphql-server/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/birdie/soapql/graphql-server/kit/webpack/browser_prod.js:57:1)
    at Module._compile (module.js:569:30)
    at loader (/home/birdie/soapql/graphql-server/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/birdie/soapql/graphql-server/node_modules/babel-register/lib/node.js:154:7) code: 'MODULE_NOT_FOUND' }

 graphql-server@0.1.0 server /home/birdie/soapql/graphql-server
 node dist/server

module.js:487
    throw err;
    ^

Error: Cannot find module '/home/birdie/soapql/graphql-server/dist/server'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

```

**Comment by leebenson** [comment]
@birdiesanders - thanks for reporting. Try it now - should work!

**Comment by birdiesanders** [comment]
It works perfectly now. Absolutely brilliant concept you guys have here. This is going to be an exciting year. Thank you for your quick response. This was my first issue raised on Github, and you made it a sublime experience. <3

**Comment by leebenson** [comment]
My pleasure. All the best with your projects.
