### ISSUE TITLE
graphql query does not work

### ISSUE THREAD

**Issue by bstaats** [reactql/examples#7]
Following the readme with `npm i` and `npm start` does not produce a successful graphql response.

There is the following error in the console from `build/server_dev.js`

```
async function send (ctx, path, opts = {}) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
```

**Comment by leebenson** [comment]
If you're getting an `async` token error, chances are you're running Node < 7.6. Try upgrading Node. If that doesn't work, feel free to re-open.
